#- name: "Reboot"
#  command: reboot

- name: "Stopping existing containers"
  command: chdir=/home/pi/clamour docker-compose stop

- name: "Removing existing containers"
  command: chdir=/home/pi/clamour docker-compose rm -f

- name: "Pulling latest version of Clamour"
  command: chdir=/home/pi/clamour docker-compose pull clamour

- name: "Starting Clamour"
  command: chdir=/home/pi/clamour docker-compose up -d
