version: '2'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  clamour:
    image: samsei/clamour:latest
    ports:
      - '10555:10555'
    privileged: true
    volumes:
      - /dev/ttyACM0:/dev/ttyACM0
