version: '2'
services:
  clamour:
    image: samsei/clamour:latest
    ports:
      - '10555:10555'
    privileged: true
    volumes:
      - /dev/ttyACM0:/dev/ttyACM0
      - /var/log/clamour:/var/log/clamour
